### ISSUE TITLE
RuntimeError always occurs while reading sensor data using `adafruit_bme680.py`

### ISSUE THREAD

**Issue by savannahcofer** [adafruit/Adafruit_CircuitPython_BME680#76]
When running `adafruit_bme680.py`, the following occurs every time.

```
Traceback (most recent call last):
File "‹stdin›", line 1, in ‹module >
File "adafruit_bme680.py", line 275, in temperature File "adafruit_bme680.py", line 394, in _perform_reading
RuntimeError: Timeout while reading sensor data
```

**Comment by caternuson** [comment]
Please post in the forums with photos of your setup showing how everything is connected:
https://forums.adafruit.com/

**Comment by caternuson** [comment]
nvm - that one is an obvious code error
